/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homeworkmodule2.gradle;

import com.google.gson.Gson;

public class App {

    public static void main(String[] args) {
        Person person = new Person("Serhii","Halun");
        Gson gson = new Gson();
        System.out.println(gson.toJson(person));

    }
    public String getGreeting() {
        return "Hello from App!";
    }
}
